### ISSUE TITLE
导入AS不能运行

### ISSUE THREAD

**Issue by ylmyg** [CCY0122/douyinloadingview#2]
请问作者是不是没有上传代码完整，导入项目报错Plugin with id 'com.android.library' not found.

**Comment by RealMoMo** [comment]
项目只有src文件夹，自己手动copy到项目就好了

**Comment by RealMoMo** [comment]
不过作者漏了attr.xml没上传

**Comment by ylmyg** [comment]
作者上传attr.xml了 ，我也直接copy到项目里面了，
